Traceback (most recent call last):
  File "c:\users\fuzzbin\.pyenv\pyenv-win\versions\3.7.6\lib\site-packages\jupyter_cache\executors\utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "c:\users\fuzzbin\.pyenv\pyenv-win\versions\3.7.6\lib\site-packages\nbclient\client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "c:\users\fuzzbin\.pyenv\pyenv-win\versions\3.7.6\lib\site-packages\nbclient\util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "c:\users\fuzzbin\.pyenv\pyenv-win\versions\3.7.6\lib\site-packages\nbclient\util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "c:\users\fuzzbin\.pyenv\pyenv-win\versions\3.7.6\lib\asyncio\base_events.py", line 583, in run_until_complete
    return future.result()
  File "c:\users\fuzzbin\.pyenv\pyenv-win\versions\3.7.6\lib\site-packages\nbclient\client.py", line 554, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "c:\users\fuzzbin\.pyenv\pyenv-win\versions\3.7.6\lib\site-packages\nbclient\client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "c:\users\fuzzbin\.pyenv\pyenv-win\versions\3.7.6\lib\site-packages\nbclient\client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Importerer n√∏dvendige biblioteker
import matplotlib.pyplot as plt
import numpy as np

# Initialbetingelser
y0 = 1
delta_t = 1

# For hvilken t skal beregningene stoppe?
max_t = 5

# Eksakt l√∏sning
def A(x, k):
    return k * np.exp(x)

# Eulers metode for denne spesifikke problemstillingen
def next_y(t, yn):
    return yn + t * yn

# x-verdier for plotting av eksakt l√∏sning
x = np.arange(0, max_t, 0.1)
y = []

# Regner ut eksakt l√∏sning
for i in x:
    y.append(A(i, y0))

# x-verdier for plotting av Euler
xe = np.arange(0, max_t, delta_t).tolist()

# Initialiserer med startverdien for ye
ye = [y0] 

# Bruker Eulers metode for √• regne ut neste y-verdi
for verdi in xe:
    ye.append(next_y(delta_t, ye[-1]))

# Legger til den siste x-verdien
xe.append(xe[-1] + delta_t)

# Utskrift av data
plt.grid() # Lager rutenett
plt.xlabel('$t$') # Merker x-aksen
plt.ylabel('$A(t)$') # Merker y-aksen
plt.plot(x, y, label='$f(x)=e^x$')
plt.plot(xe, ye, label='Euler med $\Delta t={}$'.format(delta_t))
plt.legend()
plt.show()
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mModuleNotFoundError[0m                       Traceback (most recent call last)
[1;32m<ipython-input-1-f4e65fcb6821>[0m in [0;36m<module>[1;34m[0m
[0;32m      1[0m [1;31m# Importerer n√∏dvendige biblioteker[0m[1;33m[0m[1;33m[0m[1;33m[0m[0m
[1;32m----> 2[1;33m [1;32mimport[0m [0mmatplotlib[0m[1;33m.[0m[0mpyplot[0m [1;32mas[0m [0mplt[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m      3[0m [1;32mimport[0m [0mnumpy[0m [1;32mas[0m [0mnp[0m[1;33m[0m[1;33m[0m[0m
[0;32m      4[0m [1;33m[0m[0m
[0;32m      5[0m [1;31m# Initialbetingelser[0m[1;33m[0m[1;33m[0m[1;33m[0m[0m

[1;31mModuleNotFoundError[0m: No module named 'matplotlib'
ModuleNotFoundError: No module named 'matplotlib'

